package gr.kipouralkis.backend.agent;

import gr.kipouralkis.backend.dto.Message;

import java.util.List;

/**
 * A comprehensive wrapper for the AI's output during a single reasoning turn.
 * * @param content The natural language text generated by the AI.
 * @param toolCalls A list of actions the AI intends to take.
 * @param rawMessage The original message object (including metadata) to be saved in history.
 */
public record LlmResponse(
        String content,
        List<ToolCall> toolCalls, // Changed from single to List
        Message rawMessage        // Added to keep track of the Assistant's turn
) {
    public boolean hasToolCalls() {
        return toolCalls != null && !toolCalls.isEmpty();
    }
}